export interface Reparo {
    "datarec-lab": any
    NFSerRem: string
    lote: number
    "fl-origem": string
    LabAnt: string
    preco: number
    "usuario-recebe-lab": string
    NomSirOrg: string
    nfretfe: string
    "NumSerie-ant": string
    datarecdrf: any
    SerDevol: string
    NumSerie: number
    "num-serie-it": string
    DataRecebe: string
    "vl-orcado": number
    CodCliDest: number
    Flag2: string
    datainirep: any
    "Cod-for-ext": number
    RRAnt: any
    LaudoTecnico: string[]
    RequisSaida: number
    serretfe: string
    Abertura: string
    Laboratorio: string
    "desc-item-equiv": string
    "nat-operacao": string
    "nr-enc": number
    "NumSerie-atu": string
    dtretcon: any
    "qt-equiv": number
    NumOS: number
    "nr-process": number
    DataDevol: any
    FilAnt: any
    impressa: boolean
    CodCliOrig: number
    NFDevol: string
    "nat-operacao-rem": string
    NTecnico: number
    "nr-pedido": number
    DefInd: number
    "id-orcamento": string
    "e-cliente": boolean
    "qt-reparos": number
    CidSirOrg: string
    "it-codigo-equiv": string
    clisirog: string
    ConSirOrg: string
    Aprovado: boolean
    "dt-trans": any
    "cod-estabel": string
    "est-ntecnico": string
    "usuar-recebe-exp": string
    "fm-codigo": string
    FonSirOrg: string
    NatDevol: string
    CodLab: string
    "nf-saida": string
    NFRecebe: string
    NFrem: string
    HoraRecebe: string
    UsuarioC: string
    UsuarioI: string
    sequencia: number
    NumRR: number
    dtremcon: any
    Flag: string
    "rr-bloq": boolean
    "est-ntecnicosol": string
    "data-recebe-exp": any
    "it-codigo": string
    "est-ntecnicolab": string
    "num-plan": number
    "nr-pedido-dev": number
    EndSirOrg: string
    Situacao: string
    CodFilial: string
    Atividade: string
    "nr-laudo": number
    Observacao: string
    clisirde: string
    "l-equivalente": boolean
    Chamado: number
    NFserie: string
    "it-procomp": string
    "tp-encerra": string
    localizacao: string
    EstSirOrg: string
    "serie-enc": string
    filsp: boolean
    NTecnicosol: number
    "hora-recebe-exp": string
    natretfe: string
    NTecnicolab: number
    DataRRAnt: any
}